name: Docker Image CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag vinokkk/tttt:latest 
    - name: Push the Docker image 
      run: docker login -u vinokkk -p Jin196632. && docker push vinokkk/tttt:latest

  deploy:

    runs-on: ubuntu-latest

    steps:
      - name: deploy on ECS
        uses: appleboy/ssh-action@master
        with:
          host: 124.70.39.36
          username: root
          key: ${{ secrets.SSH_SECRET }}
          passphrase: 196632
          script: pwd && cd /srv/tttt && ./deploy.sh
